%YAML 1.0
---
#data_file: freebayes_D2.filtered.rbci
data_file: freebayes_D2.NWfiltered_2.rbci
out_dir: ../mapper_test
n_res: 45
n_sus: 178
chrom: Chr04
#chrom: 
hs_max: 0.0
start: null
stop: null
with_parents: False
plots: True
dp_max_ratio: 5
trust_gatk: False
#filter_flags: PASS
filter_flags: NoSBtag,NoSBtag;NonPhasingPoolHomozygous 
min_qual: 100
resolution: 10000
phenoNoise: 1E-10
min_segr_pv: null
chrom_size: null
window_size: 5000000.0
opt_eps: False
opt_recombination: False
EMAR_SP: 3
EX_CO_Chrom: 2

